### ISSUE TITLE
Clear active column?

### ISSUE THREAD

**Issue by oldbie** [b1nj/userscripts#1]
Would it be possible to identify the active column (the one that a user's "cursor" is on) and clear that with a single key?

**Comment by b1nj** [comment]
I think, use a single key for clear a column is dangerous.
Maybe when a tweet is active (when tweet is grey with keyboard shortcuts navigation) with the key "del" ?

**Comment by oldbie** [comment]
That would be perfect, actually.

**Comment by b1nj** [comment]
It's ok.
- Del for clear active column
- 1...9 + Del for clear column 1-9
- Alt + Del for clear all

**Comment by oldbie** [comment]
Very cool! Love this. Thank you.
