### ISSUE TITLE
Delete key while composing a reply

### ISSUE THREAD

**Issue by oldbie** [b1nj/userscripts#2]
If you use the keyboard to navigate to a tweet and then hit the 'R' shortcut to reply, hitting delete will clear the column. Would it make sense to make the clear shortcut something other than delete?

**Comment by jeffsonderman** [comment]
I have submitted a pull request that fixes this issue by not acting on Delete key presses while you are typing a tweet reply.

**Comment by b1nj** [comment]
thank
