### ISSUE TITLE
New Firefox Tracking Protection blocks icon, preventing install

### ISSUE THREAD

**Issue by abmaonline** [b1nj/userscripts#5]
The new [Firefox Tracking Protection](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default) is blocking the retrieval of the icon and prevents the installation of the script (React DevTools error is not relevant):
<img width="626" alt="screen shot 2018-11-06 at 20 40 07" src="https://user-images.githubusercontent.com/4146168/48089663-509d4c80-e205-11e8-90d6-8bc6100f577f.png">

**Comment by b1nj** [comment]
Thank you.
Sorry for this late validation.
I'm now using my Firefox plugin and I did not have a problem with mustach and the icons.

https://addons.mozilla.org/fr/firefox/addon/tweetdeck-plus/
https://github.com/b1nj/webExtension/tree/master/tweetDeck
